version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_DB_URL: mongodb://mongodb:27017/mydatabase
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: