version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: sample-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
