
FROM golang:latest AS build


WORKDIR /app


COPY go.mod .


RUN go mod download


COPY . .


RUN go build -o main .


FROM alpine:latest


WORKDIR /app


COPY --from=build /app/main .


EXPOSE 8080


CMD ["./main"]
