version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: sample-db
    ports:
      - "5432:5432"
